### ISSUE TITLE
How to launch abc-export

### ISSUE THREAD

**Issue by VerenaK90** [ICB-DCM/pyABC#134]
Dear Yannik,

I am running pyABC on models written in R and storing my history in Example.db, as explained in your tutorial. However, I fail to export the database to a csv file. I tried to run 'abc-export', 'pyabc.export' and 'abc.export' upon importing pyabc in python but nothing works out.

Could you please explain in more detail, how abc-export works? Do I have to run it in python? If so, which scripts do I need to import to get the function working? A minimal example would be very helpful.

Thank you so much for your help!

Best wishes, Verena

**Comment by yannikschaelte** [comment]
Hi Verena,

``abc-export`` is defined as an additional entry point (further info: https://python-packaging.readthedocs.io/en/latest/command-line-scripts.html) into the pyabc program. That means, if you install pyabc via pip install pyabc,"abc-export" becomes available in your path on your linux system, so that you can call it directly. For how to use it, see here: https://pyabc.readthedocs.io/en/latest/export_db.html. Just type that (i.e. ``abc-export --db blabla``) in the command line (shell/bash/pycharm/...) directly, not inside python.

If your system is not linux or mac but windows, it could still work, or not. In the latter case, you can also call the underlying python command directly, from python. Let us know, then we can give you more details.

I hope this helps. If it's not clear yet, don't hesitate to write!

Best,
Yannik

**Comment by VerenaK90** [comment]
Hi Yannik,

thank you very much for the fast and detailed response - it made all very clear! And thank you for a great tool!

Best, Verena

**Comment by yannikschaelte** [comment]
Sure :)
