### ISSUE TITLE
Save more to History

### ISSUE THREAD

**Issue by yannikschaelte** [ICB-DCM/pyABC#27]
Currently, e.g. the Transition and Acceptor are not saved to history, though this would be of interest while recovering passed runs. Thus, one should add these to History during initial database setup.
**Attention**: Backwards compatibility. In particular, the abc-server uses this information.

**Comment by neuralyzer** [comment]
This is a great idea. It could be difficult to handle this in practice. E.g. how to deal with user defined transitions? Some basic logging could probably be achieved through the get_config API part which most of the Epsilon, Transition, etc. classes have (or should get in the future). The one thing which I would not do is storing pickled objects due to compatibility and security reasons.

To still handle automated loading and restoring epsilon, transitions, etc, one could think of a central registry for those classes (a factory), such that the appropriate parameters are passed to them and the right objects are created.  But, these are just some thoughts...

**Comment by yannikschaelte** [comment]
Totally agree, we were planning to use/implement the get_config methods for all objects which are represented as classes in pyabc. Pickling will not be used.

We already discussed that it will be impossible to store and restore on load() all information, in particular user-defined and adaptive parts. Our idea was to store and restore as much as adequate (e.g. static information, and restore via the initialize methods, which are now also called upon load()), but to make it the responsibility of the user to store e.g. the entire used distance and eps objects, in order to be able to analyze or continue later without any information loss. Storing all this information per default in the pyabc database is impossible, due to space requirements and flexibility. Maybe we will find some solution here as well, but for now this is not planned.

Idea of central registry or similar will be kept in mind, thanks.

**Comment by yannikschaelte** [comment]
Of particular interest: Save the current pyabc version to db (when a new population is created). I think that info is contained no-where yet.

**Comment by yannikschaelte** [comment]
Closed now since too generic. Probably a new data format will need to be introduced anyway due to some add-ons, and then we will see what all to store.
