### ISSUE TITLE
abc.run stuck at t=1 for integer parameters

### ISSUE THREAD

**Issue by sisyga** [ICB-DCM/pyABC#329]
Hi, so if for models with integer parameters the abc.run gets stuck at t=1 without running the model. Weirdly, there is no error message or crush. Maybe there is an issue with the transition kernel for integer parameters. The problem can be circumvented by using a float parameter that gets rounded to the next integer, however, it still consider the current behavior a bug.
Here's a MWE:

```
import pyabc
from pyabc.sampler import SingleCoreSampler
import numpy as np
import tempfile
import os
import matplotlib.pyplot as plt

def model(par):
    # print('new run!')
    return {"data": np.random.binomial(par['n'], 0.5)}

def distance(x, y):
    return abs(x["data"] - y["data"])

prior = pyabc.Distribution(n=pyabc.RV("randint", 1, 21))  # it works if I switch to 'uniform'
abc = pyabc.ABCSMC(model, prior, distance, sampler=SingleCoreSampler())  # SingleCoreSampler because I am on Windows

db_path = ("sqlite:///" +
           os.path.join(tempfile.gettempdir(), "test.db"))
observation = 5
abc.new(db_path, {"data": observation})
history = abc.run(minimum_epsilon=0., max_nr_populations=10)


fig, ax = plt.subplots()
for t in range(1, history.max_t+1, 2):
    df, w = history.get_distribution(m=0, t=t)
    pyabc.visualization.plot_kde_1d(
        df, w,
        xmin=0, xmax=20,
        x="n", ax=ax,
        label="PDF t={}".format(t))
plt.legend()
plt.show()
```

I am on Windows 10x64 with the latest Anaconda environment, where I installed pyabc via pypi. My pyabc version is 0.10.4.

**Comment by yannikschaelte** [comment]
Hi @sisyga , I see now what the problem is. It is that in its sequential population-based approach, pyABC uses by default a multivariate normal kernel as transition function. This can be modified by passing another [transition](https://github.com/ICB-DCM/pyABC/blob/master/pyabc/smc.py#L108). Any transition in [the transition module](https://github.com/ICB-DCM/pyABC/tree/master/pyabc/transition) (or self-defined derived classes) are possible here.

Before performing simulations, pyABC for efficiency checks whether the resulting importance sampling weight, which is prior divided by transition, is non-zero. As your prior has positive mass only on integer points, this leads to a practically eternal loop. There are indeed two solutions. First, as you pointed out you can take a uniform prior and round all parameters in the model to the nearest integer. Advantage: pyABC, like all implementations I know of, are tailored to continuous variables, so this way you can make use of the highly tuned algorithms for continuous scenarios. Disadvantage: The resulting weights may be statistically not completely correct, as they miss the rounding step.

Second, one can use a discrete proposal. In pyABC we have implemented a [random walk based transition](https://github.com/ICB-DCM/pyABC/blob/master/pyabc/transition/randomwalk.py), which is a standard for discrete transitions, however is not really properly tested. It may be worth a shot, but I am afraid it may not perform overly well.

In general, discrete parameters is a re-occurring issue which we hope to be able to have a well-working solution for in pyABC at some point, but unfortunately this will not be possible in, say, the next two months. We would be happy to further discuss with you though, in particular regarding applications.

**Comment by yannikschaelte** [comment]
Question: Is your parameter state space finite? In that case I could imagine a simpler solution which may be rather straightforward to implement.

**Comment by sisyga** [comment]
Hi @yannikschaelte , thanks for your reply. So indeed that is the problem I suspected. However I still think there should be some kind of fallback/warning if the loop is not converging.

In am not sure what you mean by finite parameter state space. In my application I actually have a mix of integer and float parameters, which are all (effectively) bounded.

**Comment by yannikschaelte** [comment]
Hi @sisyga , we will add a warning in case too many failed samples are detected, thanks for pointing this out. Detecting problems a-prior will unfortunately not be possible, as pyABC knows nothing about the support of the distribution.

As all of your parameters are bounded, I think it should be possible to define a new proposal distribution which uses a multivariate Gaussian one for continuous parameters, and a simple weighted discrete resampling for the discrete ones (i.e. a sampling according to the estimated posterior probabilities of each of the discrete values). The state space being finite makes this possible, i.e. the random walk will not be needed. One would need to add a small positive weight in case some points have weight zero, to obtain an absolutely continuous transition kernel.

If you think the latter is of interest for you, let us know, then we can discuss in more detail.

**Comment by sisyga** [comment]
Thank you @yannikschaelte , that sounds very promising, I will contact you via email about it!

**Comment by yannikschaelte** [comment]
done in #331
