### ISSUE TITLE
The basic parameter learning example does not work

### ISSUE THREAD

**Issue by daviddewhurst** [ICB-DCM/pyABC#347]
OS: OSX Catalina 10.15.6
Environment: Anaconda 3.7, `requirements.txt` attached

Issue: the example does not work. Pasting code from the demo in a jupyter notebook gives a `ValueError` with the traceback indicating a pickle / dill / cloudpickle problem: `Cell is empty`:
```
ValueError                                Traceback (most recent call last)
<ipython-input-2-8a22ef36d827> in <module>
     16 abc.new(db_path, {"data": observation})
     17 
---> 18 history = abc.run(minimum_epsilon=.1, max_nr_populations=10)

/opt/anaconda3/lib/python3.7/site-packages/pyabc/inference/smc.py in run(self, minimum_epsilon, max_nr_populations, min_acceptance_rate)
    604         self._adapt_population_size(t0)
    605         # sample from prior to calibrate distance, epsilon, and acceptor
--> 606         self._initialize_dist_eps_acc(t0)
    607 
    608         # configure recording of rejected particles
...
/opt/anaconda3/lib/python3.7/site-packages/dill/_dill.py in save_cell(pickler, obj)
   1167 def save_cell(pickler, obj):
   1168     log.info("Ce: %s" % obj)
-> 1169     f = obj.cell_contents
   1170     pickler.save_reduce(_create_cell, (f,), obj=obj)
   1171     log.info("# Ce")

ValueError: Cell is empty

```
 Instead pasting code into a file and running with `/opt/anaconda3/envs/pyabc-env/bin/python pyabc-error.py` gives a much longer sequence of parallel sampling errors; see attached `error.txt`.

[error.txt](https://github.com/ICB-DCM/pyABC/files/5257249/error.txt)

Maybe I am missing something -- hopefully this is the case. As of now I am not sure what is going wrong but the package is unusable for me. Hopefully this is a silly error on my part that you could help me understand.

**Comment by daviddewhurst** [comment]
Forgot `requirements.txt`: 
[requirements.txt](https://github.com/ICB-DCM/pyABC/files/5257292/requirements.txt)

**Comment by yannikschaelte** [comment]
Hi, at first glance this looks related to differences in python's implementation of multiprocessing on MacOS vs Linux. Since recently, we support MacOS (https://github.com/ICB-DCM/pyABC/runs/1101199633?check_suite_focus=true), however do not maintain an own test system, therefore debugging is a bit difficult.

First, you should be able to at least run pyABC by changing the sampler to `sampler=pyabc.SingleCoreSampler()` (pass to `ABCSMC`, see also https://pyabc.readthedocs.io/en/latest/sampler.html). This will perform all simulations sequentially.

Single core execution will be quite slow, given your 16 core system. Therefore, second you might try out passing `sampler=pyabc.MulticoreEvalParallelSampler(pickle=True)`. This is the default multiprocessing sampler, except with pickling enabled, which is marginally slower, depending on the model, but has a higher chance of working on Mac.

If option 2 fails, it may be worthwhile to set up a redis server via `sampler=pyabc.RedisEvalParallelSampler`, which then takes over the job distribution, see the linked documentation for details. Efficiency-wise, there should be no difference to option 2.

Hope this helps!

**Comment by daviddewhurst** [comment]
Thanks for this update -- `SingleCoreSampler` works fine, while `MulticoreEvalParallelSampler` gives me the same pickling issue. I haven't tried Redis yet but I can update you if you're interested.

**Comment by yannikschaelte** [comment]
Well, if single core execution is fine for you, that would suffice. If you want to parallelize, either redis or the MultiCoreEvalParallel sampler would need to be made running.

Note that our test system uses python 3.8, which may behave differently on Mac.

**Comment by daviddewhurst** [comment]
Great. If those methods continue to generate errors on macOS and upgrading to 3.8 doesn't fix it, I might try to patch + PR. Thanks for the help!

**Comment by yannikschaelte** [comment]
> Great. If those methods continue to generate errors on macOS and upgrading to 3.8 doesn't fix it, I might try to patch + PR. Thanks for the help!

That would definitely be welcome!
