### ISSUE TITLE
Redis server waits for killed workers

### ISSUE THREAD

**Issue by yannikschaelte** [ICB-DCM/pyABC#38]
Sometimes the redis server reportedly does not get notified when one of its workers got killed, and then waits for eternity for this worker to come back. 

When exactly this happens has not been reproduced yet.

**Comment by neuralyzer** [comment]
Does the redis server ever get notified when a worker dies? There is no heartbeating, I think. Was one added in the meantime? The reason there was (initially?) no heartbeating is that heartbeating caused troubles in slow network settings. But it might still be a good idea to add one.

**Comment by yannikschaelte** [comment]
The problem was reported to me, and I have not reproduced it, but I think a major issue might be that a worker is started so early that the master has to wait for it to return by the rules of dynamic scheduling, and then if it just got killed in the meantime the master waits forever. Do you think that might happen?

**Comment by neuralyzer** [comment]
I do believe that this might indeed happen. Maybe you can use fuzzing to debug this? In essence you'd place random sleep times at different locations of the code, hoping that some combination of execution order leads to reproduce the bug. If the bug occurs in the Redis sampler it is quite likely that is also occurs in the Multiprocessing Eval Parallel sampler. Maybe have a look at this talk by Raymond Hettingger on parallel (Python) programming. He talks a little about the difficulties involved and how to do fuzzing: https://www.youtube.com/watch?v=9zinZmE3Ogk

**Comment by elbaraim** [comment]
I am currently having this problem when running ML-rules using [SESSL](https://git.informatik.uni-rostock.de/mosi/sessl-quickstart). May be good to add an automatic check (if possible), so that if the number of workers is reduced, a reset-worker is automatically  performed (?) What do you think about this?

**Comment by neuralyzer** [comment]
Hi,

in general, determining if a worker is dead is a hard problem to solve. Network communication is inherently unreliable. So you can never know if the network is slow or the worker is dead. Also, simulations can take an arbitrary amount of time. The solution to this problem which is most frequently applied, I think, is to do some kind of heartbeating. E.g. have each and every worker send a message every couple seconds (minutres). Declare the worker dead if the message does not arrive on time. If you go this way, you will also need to take care of workers which were erroneously declared dead and became alive again. Make sure these resurrected workers won't cause trouble and manage to resume processing correctly.

You might also want to check dask again. I think it has made quite some progress since the start of pyABC. Dask implements heartbeating. On the rather slow ICB network, the heartbeats themselves were however causing trouble. Most of the worker got erroneously declared dead because the network could not handle the many heartbeats.

If you need more inspiration, you might also want to check projects such as Kafka, Flink or Storm which implement various strategies to implement "at least once" or "exactly once" delivery and processing guarantees. Although they don't solve exactly the same problem you're trying to solve, it might give you an idea.

**Comment by yannikschaelte** [comment]
I think we have to distinguish 2 things here: either the node gets killed because there is some error in the model/sumstat/distance step, or something else causes the node to die unexpectedly (like an external max timer). 

the second case can only be handled by some form of heartbeating, which will be problematic on slow networks. the first case however we should be able to simply treat by capturing any errors happening in the ``simulate_one()`` step and just treating this evaluation as not-accepted.

**Comment by yannikschaelte** [comment]
fixed via #145
