### ISSUE TITLE
Setting a seed

### ISSUE THREAD

**Issue by frank-pieterse** [ICB-DCM/pyABC#392]
Hi,

As a part of my analysis, i wanted to see the difference between different threshold schemes starting from the same initial population of particles. If i understand correctly, setting a seed for the RNG would give me the same initial population each time (it would also make it reproducible). I tried to set the seed via the numpy and random packages, but those don't seem to fix the outcome (even with the same settings).

How can i set a seed before running pyABC to get reproducible output?

Thanks in advance.
Kind regards,
Frank

**Comment by yannikschaelte** [comment]
Hi @frank-pieterse , in order to have independent simulations, at the moment when employing parallelization, each of the workers initializes an own random seed. Thus, setting the random seed on your main thread does not affect the simulations unfortunately, unless you employ a SingleCoreSampler.

What one would need to do is allow passing a random seed to the main thread, and then generating seeds from that (e.g. np.random.randint()) to be used as random seeds by the workers, whenever new processes are spawned, or in each population. However, even then the result would not be deterministic, as it depends on which worker contributes how many results (which depends on e.g. the relative speed and load of CPUs). So, it might be more deterministic, but probably not completely. Only with the SingleCoreSampler, determinism can be guaranteed.

If using the SingleCoreSampler is not an option for you and the degree of determinism should be increased, we can try to implement seeding soonishly for all samplers. What do you think?

**Comment by frank-pieterse** [comment]
Hi @yannikschaelte,

Thanks for the reply!

For my purpose, the SingleCoreSampler is an option. It will be a bit slower, but it will get the job done. 
I wanted to see if changing the quantile in the QuantileEpsilon makes a big difference when starting from the same population. For that purpose, I won't be needing a lot of computational power. I don't think the seeding for all the samplers is necessary., unless you can think of another good reason to do so.
