### ISSUE TITLE
Runtime parameter not working in Redis worker

### ISSUE THREAD

**Issue by pranay-jain** [ICB-DCM/pyABC#396]
Hi, I'm using pyABC for a research project. I'm running it on a High-Performance Cluster using Redis-based distributed sampling. I've been following the documentation [here](https://pyabc.readthedocs.io/en/latest/sampler.html) and so far it's been working fine. I'm facing an issue that the `abc-redis-worker` does not obey the `--runtime` parameter passed to it. My setup is over 2 HPC clusters. One of them belongs to my university which I use to run the long-running master process and the redis server. The second one is used for launching worker jobs.

To test this, I launched a worker process using the following command: `abc-redis-worker --host=<hostname> --port=<port> --runtime=10m`. Upon launching I see the output `INFO:REDIS-WORKER:Start redis worker. Max run time 600.0s, PID=<pid>`. But despite this, the worker keeps on running for longer than 10 minutes, until it's given the kill command (or the job reaches its max time limit). This is causing problems as the abc-redis-manager still sees the workers as connected workers and I have to run  `abc-redis-manager reset-workers` every once in a while to reset them and start anew.

Let me know if I can provide any more information. Thanks!

**Comment by yannikschaelte** [comment]
Hi @pranay-jain , just to clarify: Is this a problem that was recently introduced and did not exist in a previous version? Or are you not aware of this being version specific?

I think this may be due to the process block-waiting for input [here](https://github.com/ICB-DCM/pyABC/blob/master/pyabc/sampler/redis_eps/cli.py#L105), and not regularly checking the time criterion. This could be improved by not blocking, but adding sleep intervals.

**Comment by pranay-jain** [comment]
Hi @yannikschaelte thanks for the quick response. It's not something that was recently introduced. I've been working on version 0.10.9 the whole time, so I'm not aware if it's a version specific issue. But your suggestion might be correct. In my case, the generation model is a very long process, so there is probably no message being passed to redis for long periods of time. If a worker job ends during this period, then the job will just end without abc-redis-manager knowing about it.

**Comment by yannikschaelte** [comment]
Hi @pranay-jain , sorry for the delay. The `--runtime` criterion is regularly checked [here](https://github.com/ICB-DCM/pyABC/blob/master/pyabc/sampler/redis_eps/cli.py#L139) after a population and [here](https://github.com/ICB-DCM/pyABC/blob/master/pyabc/sampler/redis_eps/work.py#L95) during a population, in between single simulations. In your case it sounds like the model simulation takes a long time (is it >>10min?), such that the total time exceeds the time the cluster manager has granted the process, so that it is just killed. Currently, the redis server has no way of learning of workers that were externally killed and keeps waiting for their return message. Therefore, one would ideally want to check all workers at regular intervals whether they are still alive. However, this would be non-trivial, as on a cluster there can occur delays in message processing, therefore we have not implemented that yet, and for a model where problems sometimes occurred, just manually called `redis-manager reset-workers` once in a while.

**Comment by pranay-jain** [comment]
Yes, the model simulation for my case takes >> 10mins. So, I understand that if there's a problem in one of the model workers, I can run `redis-manager reset-workers`, which would essentially disconnect all workers and I'd need to restart new workers. However, after diving further into my issue I realized that there's a more serious problem. If the model takes a long time to complete, the model process is actually disconnected from the Redis server. So, once the model completes running, it sends a message to Redis, it receives an error response: `redis.exceptions.ConnectionError: Error while reading from socket: (104, 'Connection reset by peer')`. So, the model is in fact not even able to submit the result of the generation back. I found a possible solution to this [here](https://github.com/andymccurdy/redis-py/issues/1186). They suggest adding a `health_check_interval=n` argument to the StrictRedis object when it's initialized such as [here](https://github.com/ICB-DCM/pyABC/blob/ba0fbaecd828908c244cfbaa62982c69329668e8/pyabc/sampler/redis_eps/cli.py#L95). I'm trying to test it out locally, but perhaps this might solve it?

**Comment by yannikschaelte** [comment]
Hi @pranay-jain , not sure if the connection instability is a problem of the redis server, or of the infrastructure. @EmadAlamoudi didn't you also report "Connection reset by peer" issues? The health checks (or also some sort of heart beating) might be a solution then.

**Comment by yannikschaelte** [comment]
Closing as open for a long time and we did not observe any problems in the meantime. If errors persist, please re-open!
